/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CadastroVO;
import servicos.CadastrarServicos;
import servicos.ServicosFactory;

/**
 *
 * @author 181700028
 */
public class GUIManutencaoUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIManutencaoUsuario
     */
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código","Nome","Email","Login","Senha","Cpf","Endereco","Cep","Telefone","Discord","Steam","Jogo1","Jogo2","Jogo3","Jogo4","Jogo5"}
    );
    public GUIManutencaoUsuario() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void preencherTabela(){
        
        try {
            //Buscando objeto na CadastroServicos
            CadastrarServicos cs = ServicosFactory.getCadastrarServicos();
            
            //Criando um ArrayList<CadastroVO> vazio para receber o arrayList com os dados da CadastroServicos
            ArrayList<CadastroVO> prod = new ArrayList<>();
            
            //Recebendo o ArrayList cheio do usuario
            prod = cs.buscarUsuario(); 
            
            for(int i = 0; i < prod.size(); i++){
                dtm.addRow(new String[] {
                    String.valueOf(prod.get(i).getIdCadastro()),
                    String.valueOf(prod.get(i).getNome()),
                    String.valueOf(prod.get(i).getEmail()),
                    String.valueOf(prod.get(i).getLogin()),
                    String.valueOf(prod.get(i).getPassword()),
                    String.valueOf(prod.get(i).getCpf()),
                    String.valueOf(prod.get(i).getEndereco()),
                    String.valueOf(prod.get(i).getCep()),
                    String.valueOf(prod.get(i).getTelefone()),
                    String.valueOf(prod.get(i).getDiscord()),
                    String.valueOf(prod.get(i).getSteam()),
                    String.valueOf(prod.get(i).getJogo1()),
                    String.valueOf(prod.get(i).getJogo2()),
                    String.valueOf(prod.get(i).getJogo3()),
                    String.valueOf(prod.get(i).getJogo4()),
                    String.valueOf(prod.get(i).getJogo5()),
                });
            }//fim do laço for
            
            //Adicionando modelo de tabela com os dados na tabela jtUsuarios
            jtUsuarios.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro! GUIManutencaoUsuarios.preencherTabela"+ e.getMessage());
        }//fim do catch
        
    }//fim preencherTabela
    
    private void limparTabela(){
        
        dtm.setNumRows(0);
        
    }//fim limparTabela
    
    private void filtrar(){
        
        try {
            if(jtfPesquisaPro.getText().isEmpty()){
                preencherTabela();
            }else{
                CadastrarServicos cs = ServicosFactory.getCadastrarServicos();
                String pesquisa = (String) jcbPesquisaPro.getSelectedItem();
                String query;
                
                if(pesquisa.equals("Código")){
                    query = "where idcadstro = " + jtfPesquisaPro.getText();//para numero só where
                }else if(pesquisa.equals("Nome")){
                    query = "where nome = '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Email")){
                    query = "where email '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Login")){
                    query = "where login '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Password")){
                    query = "where password '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Cpf")){
                    query = "where cpf like '%" + jtfPesquisaPro.getText() + "%' "; //para string se usa like '%palavra%'
                }else if(pesquisa.equals("Endereco")){
                    query = "where endereco '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Cep")){
                    query = "where cep '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Telefone")){
                    query = "where telefone '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Discord")){
                    query = "where discord '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Steam")){
                    query = "where steamfriend '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Jogo1")){
                    query = "where jogos1 '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Jogo2")){
                    query = "where jogos2 '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Jogo3")){
                    query = "where jogos3 '%"+ jtfPesquisaPro.getText() + "%' ";
                }else if(pesquisa.equals("Jogo4")){
                    query = "where jogos4 '%"+ jtfPesquisaPro.getText() + "%' ";
                }else{
                    query = "where jogos5 = "+ jtfPesquisaPro.getText() + "%' ";
                }//fim do if else if
                
                //Criando ArrayList vazio para receber os dados do ArrayList
                ArrayList<CadastroVO> col = new ArrayList<>();
                
                //Recebendo o ArrayList cheio do produto
                col = cs.filtrarUsuario(query);
                
                for(int i = 0; i < col.size(); i++){
                    dtm.addRow(new String[]{ 
                    String.valueOf(col.get(i).getIdCadastro()),
                    String.valueOf(col.get(i).getNome()),
                    String.valueOf(col.get(i).getEmail()),
                    String.valueOf(col.get(i).getLogin()),
                    String.valueOf(col.get(i).getPassword()),
                    String.valueOf(col.get(i).getCpf()),
                    String.valueOf(col.get(i).getEndereco()),
                    String.valueOf(col.get(i).getCep()),
                    String.valueOf(col.get(i).getTelefone()),
                    String.valueOf(col.get(i).getDiscord()),
                    String.valueOf(col.get(i).getSteam()),
                    String.valueOf(col.get(i).getJogo1()),
                    String.valueOf(col.get(i).getJogo2()),
                    String.valueOf(col.get(i).getJogo3()),
                    String.valueOf(col.get(i).getJogo4()),
                    String.valueOf(col.get(i).getJogo5()),
                    });
                }//fecha o for
                
                //Adicionar o modelo de tabela com os dados da tabela jtUsuarios
                jtUsuarios.setModel(dtm);
                
            }//fim do if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao filtrar usuarios!GUIManutencãoUsuarios.filtrar" + e.getMessage());
        }
        
    }//fecha o filtrar
    
    private void deletarUsuario(){
        try {
            int linha = jtUsuarios.getSelectedRow();
            
            if(linha == -1){
                JOptionPane.showMessageDialog(null,
                        "Por favor selecione uma linha!");
            }else{               
                int resposta = JOptionPane.showConfirmDialog(null,
                        "Deseja mesmo deletar o usuario selecionado?",
                        "Deletar usuario",
                        JOptionPane.YES_NO_OPTION);
                if(resposta == JOptionPane.YES_OPTION){                   
                    CadastrarServicos cs = ServicosFactory.getCadastrarServicos();
                    String codUsuario = (String) jtUsuarios.getValueAt(linha, 0);
                    cs.deletarUsuario(Long.parseLong(codUsuario));
                
                    //Mensagem para o usuário
                    JOptionPane.showMessageDialog(null,
                        "usuario excluido com sucesso!");   
                }else{                   
                    JOptionPane.showMessageDialog(null,
                            "usuario não excluido");
                }//fim if else              
            }//fim do if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao deletar usuario!GUIManutencaoUsuario.deletar" + e.getMessage());
        }
    }
    private void alterarUsuario(){
        int linha = jtUsuarios.getSelectedRow();
        if(linha != -1){
            jtfCodigo.setText((String) jtUsuarios.getValueAt(linha, 0));
            jtfNome.setText((String) jtUsuarios.getValueAt(linha, 1));
            jtfEmail.setText((String) jtUsuarios.getValueAt(linha, 2));
            jtfLogin.setText((String) jtUsuarios.getValueAt(linha, 3));
            jtfPassword.setText((String) jtUsuarios.getValueAt(linha, 4));
            jtfCPF.setText((String) jtUsuarios.getValueAt(linha, 5));
            jtfEndereco.setText((String) jtUsuarios.getValueAt(linha, 6));
            jtfCep.setText((String) jtUsuarios.getValueAt(linha, 7));
            jtfTelefone.setText((String) jtUsuarios.getValueAt(linha, 8));
            jtfDiscord.setText((String) jtUsuarios.getValueAt(linha, 9));
            jtfSteam.setText((String) jtUsuarios.getValueAt(linha, 10));
            jtfJogo1.setText((String) jtUsuarios.getValueAt(linha, 11));
            jtfJogo2.setText((String) jtUsuarios.getValueAt(linha, 12));
            jtfJogo3.setText((String) jtUsuarios.getValueAt(linha, 13));
            jtfJogo4.setText((String) jtUsuarios.getValueAt(linha, 14));
            jtfJogo5.setText((String) jtUsuarios.getValueAt(linha, 15));
            
        }else{
            JOptionPane.showMessageDialog(
                    null,
                    "Você não selecionou nenhuma linha!");
        }//fecha o if else
    }//fim do método alterarUsuario
    
    
    public void confirmarAlteracao(){
        try {
            CadastroVO cVO = new CadastroVO();
            if(jtfNome.getText().isEmpty() ||
                    jtfEmail.getText().isEmpty() ||
                    jtfLogin.getText().isEmpty() || 
                    jtfPassword.getText().isEmpty() ||
                    jtfCPF.getText().isEmpty() ||
                    jtfEndereco.getText().isEmpty() || 
                    jtfCep.getText().isEmpty() ||
                    jtfTelefone.getText().isEmpty() ||
                    jtfDiscord.getText().isEmpty() ||
                    jtfSteam.getText().isEmpty() ||
                    jtfJogo1.getText().isEmpty() || 
                    jtfJogo2.getText().isEmpty() ||
                    jtfJogo3.getText().isEmpty() ||
                    jtfJogo4.getText().isEmpty() ||
                    jtfJogo5.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Erro! Por favor insira as informações corretamente!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }else{
                cVO.setIdCadastro(Integer.parseInt(jtfCodigo.getText() ) );
                cVO.setNome(jtfNome.getText() );
                cVO.setEmail(jtfEmail.getText() );
                cVO.setLogin(jtfLogin.getText() );
                cVO.setPassword(jtfPassword.getText()  );
                cVO.setCpf(jtfCPF.getText() );
                cVO.setEndereco(jtfEndereco.getText()  );
                cVO.setCep(jtfCep.getText()  );
                cVO.setTelefone(jtfTelefone.getText()  );
                cVO.setDiscord(jtfDiscord.getText() );
                cVO.setSteam(jtfSteam.getText()  );
                cVO.setJogo1(jtfJogo1.getText()  );
                cVO.setJogo2(jtfJogo2.getText()  );
                cVO.setJogo3(jtfJogo3.getText()  );
                cVO.setJogo4(jtfJogo4.getText() );
                cVO.setJogo5(jtfJogo5.getText()  );
                
                CadastrarServicos cs = ServicosFactory.getCadastrarServicos();
                cs.alterarUsuario(cVO);
                
                JOptionPane.showMessageDialog(
                        null,
                        "usuario alterado com sucesso!");
            }//fim do if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro!" + e.getMessage());
        }
    }//fim do método confirmarAlteracao
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbtnPreencher = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jbtnConfirmarAlteracao = new javax.swing.JButton();
        jtfEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfDiscord = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfSteam = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfJogo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfJogo2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfJogo4 = new javax.swing.JTextField();
        jtfJogo3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfJogo5 = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jtfPesquisaPro = new javax.swing.JTextField();
        jcbPesquisaPro = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });

        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });

        jbtnDeletar.setText("Deletar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });
        jbtnDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnDeletarKeyPressed(evt);
            }
        });

        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });
        jbtnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnAlterarKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jbtnPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnPreencher)
                .addGap(132, 132, 132)
                .addComponent(jbtnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(jbtnAlterar)
                .addGap(152, 152, 152)
                .addComponent(jbtnDeletar)
                .addGap(22, 22, 22))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPreencher)
                    .addComponent(jbtnLimpar)
                    .addComponent(jbtnDeletar)
                    .addComponent(jbtnAlterar))
                .addContainerGap())
        );

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "Login", "Senha", "Cpf", "Endereco", "Cep", "Telefone", "Discord", "Steam", "Jogo1", "Jogo2", "Jogo3", "Jogo4", "Jogo5"
            }
        ));
        jScrollPane1.setViewportView(jtUsuarios);

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Login");

        jLabel2.setText("Email:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Código:");

        jtfCodigo.setEditable(false);
        jtfCodigo.setFocusable(false);

        jbtnConfirmarAlteracao.setText("Confirmar Alteração");
        jbtnConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarAlteracaoActionPerformed(evt);
            }
        });
        jbtnConfirmarAlteracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnConfirmarAlteracaoKeyPressed(evt);
            }
        });

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha");

        jLabel7.setText("CPF");

        jLabel8.setText("Enderco");

        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });

        jtfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCPFActionPerformed(evt);
            }
        });

        jtfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoActionPerformed(evt);
            }
        });

        jLabel10.setText("CEP");

        jLabel11.setText("Telefone");

        jtfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefoneActionPerformed(evt);
            }
        });

        jLabel12.setText("Discord");

        jLabel13.setText("Steam");

        jtfSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSteamActionPerformed(evt);
            }
        });

        jLabel14.setText("Jogo1");

        jtfJogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJogo1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Jogo2");

        jtfJogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJogo2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Jogo4");

        jtfJogo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJogo4ActionPerformed(evt);
            }
        });

        jtfJogo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJogo3ActionPerformed(evt);
            }
        });

        jLabel17.setText("Jogo3");

        jLabel18.setText("Jogo5");

        jtfJogo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJogo5ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfDiscord, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfSteam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfJogo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfJogo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfJogo4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfJogo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfJogo5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfEmail)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCep)
                            .addComponent(jtfTelefone)
                            .addComponent(jtfDiscord, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfSteam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfJogo1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfJogo2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfJogo3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfJogo4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jtfJogo5, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnConfirmarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfDiscord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfSteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfJogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtfJogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtfJogo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnConfirmarAlteracao)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtfJogo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        jLayeredPane4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Pesquisa:");

        jtfPesquisaPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisaProKeyReleased(evt);
            }
        });

        jcbPesquisaPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "CPF", "Genero", "Rua", "Numero", "Complemento", "Status" }));
        jcbPesquisaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPesquisaProActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtfPesquisaPro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jcbPesquisaPro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtfPesquisaPro)
                .addGap(18, 18, 18)
                .addComponent(jcbPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane2)
                            .addComponent(jScrollPane1))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnPreencherActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        deletarUsuario();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jbtnDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnDeletarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            deletarUsuario();
            limparTabela();
            preencherTabela();
        }
    }//GEN-LAST:event_jbtnDeletarKeyPressed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        alterarUsuario();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnAlterarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            alterarUsuario();
        }
    }//GEN-LAST:event_jbtnAlterarKeyPressed

    private void jbtnConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarAlteracaoActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnConfirmarAlteracaoActionPerformed

    private void jbtnConfirmarAlteracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnConfirmarAlteracaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmarAlteracao();
            limparTabela();
            preencherTabela();
        }
    }//GEN-LAST:event_jbtnConfirmarAlteracaoKeyPressed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void jtfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCPFActionPerformed

    private void jtfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoActionPerformed

    private void jtfPesquisaProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaProKeyReleased
        // Evento quando clica no barra de pesquisa
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtfPesquisaProKeyReleased

    private void jcbPesquisaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPesquisaProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPesquisaProActionPerformed

    private void jtfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefoneActionPerformed

    private void jtfSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSteamActionPerformed

    private void jtfJogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJogo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJogo1ActionPerformed

    private void jtfJogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJogo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJogo2ActionPerformed

    private void jtfJogo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJogo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJogo4ActionPerformed

    private void jtfJogo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJogo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJogo3ActionPerformed

    private void jtfJogo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJogo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJogo5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnConfirmarAlteracao;
    private javax.swing.JButton jbtnDeletar;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnPreencher;
    private javax.swing.JComboBox<String> jcbPesquisaPro;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDiscord;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfJogo1;
    private javax.swing.JTextField jtfJogo2;
    private javax.swing.JTextField jtfJogo3;
    private javax.swing.JTextField jtfJogo4;
    private javax.swing.JTextField jtfJogo5;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfPesquisaPro;
    private javax.swing.JTextField jtfSteam;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
