/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import com.sun.glass.events.KeyEvent;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 181700028
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {

    //Variaveis que vão verificar se a janela esta aberta
    private boolean flagGUICadastrar = false;
    private boolean flagGUIManutencaoUsuario = false;
    
    
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmtCadastrar = new javax.swing.JMenuItem();
        ManutUsuario = new javax.swing.JMenu();
        jmtManutencaoUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jmCadastrar.setText("Cadastrar");

        jmtCadastrar.setText("Cadastrar");
        jmtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtCadastrarActionPerformed(evt);
            }
        });
        jmtCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmtCadastrarKeyPressed(evt);
            }
        });
        jmCadastrar.add(jmtCadastrar);

        jMenuBar1.add(jmCadastrar);

        ManutUsuario.setText("Manutencao");

        jmtManutencaoUsuario.setText("Manutencao Usuario");
        jmtManutencaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtManutencaoUsuarioActionPerformed(evt);
            }
        });
        jmtManutencaoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmtManutencaoUsuarioKeyPressed(evt);
            }
        });
        ManutUsuario.add(jmtManutencaoUsuario);

        jMenuBar1.add(ManutUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void abrirGUICadastrar() {
        if (!flagGUICadastrar) { //not()! com false = true --> pergunta se o flag é verdadeiro
            GUICadastrar gcp = new GUICadastrar();
            jdpAreaDeTrabalho.add(gcp);
            gcp.setVisible(true);
            
            flagGUICadastrar = true;            
            gcp.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIManutencaoUsuario(){
        if(!flagGUIManutencaoUsuario){
            GUIManutencaoUsuario gmc = new GUIManutencaoUsuario(); 
            jdpAreaDeTrabalho.add(gmc);
            gmc.setVisible(true);
            
            flagGUIManutencaoUsuario = true;
            gmc.addInternalFrameListener(this);
        }
    }
    private void jmtManutencaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtManutencaoUsuarioActionPerformed
         abrirGUIManutencaoUsuario();
    }//GEN-LAST:event_jmtManutencaoUsuarioActionPerformed

    private void jmtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtCadastrarActionPerformed
         abrirGUICadastrar();
    }//GEN-LAST:event_jmtCadastrarActionPerformed

    private void jmtCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmtCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUICadastrar();
        }
    }//GEN-LAST:event_jmtCadastrarKeyPressed

    private void jmtManutencaoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmtManutencaoUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirGUIManutencaoUsuario();
        }
    }//GEN-LAST:event_jmtManutencaoUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ManutUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenuItem jmtCadastrar;
    private javax.swing.JMenuItem jmtManutencaoUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
       
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if(ife.getInternalFrame() instanceof GUIManutencaoUsuario){
            flagGUIManutencaoUsuario = false;
        }
        if(ife.getInternalFrame() instanceof GUICadastrar){
            flagGUICadastrar= false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
       
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
       
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
